language: en

pipeline:
  # - name: components.preprocessors.ExcludePreprocessor
  #   exclude: ",-."
  - name: components.preprocessors.W2NPreprocessor
  - name: WhitespaceTokenizer
  - name: LanguageModelFeaturizer
  - name: RegexFeaturizer
    case_sensitive: False
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    constrain_similarities: True
    epochs: 200
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 5
