language: en

pipeline:  
  - name: SpacyNLP
    model: "en_core_web_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  # - name: RegexEntityExtractor
  #   case_sensitive: False
  #   use_lookup_tables: True
  #   use_regexes: True
  - name: EntitySynonymMapper
  - name: SklearnIntentClassifier



policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 5
