language: en

# pipeline:
#   - name: "components.preprocessors.ExcludePreprocessor"
#   - name: SpacyNLP
#     model: "en_core_web_lg"
#   - name: SpacyTokenizer 
#   - name: SpacyFeaturizer
#   - name: RegexFeaturizer
#     case_sensitive: False
#   - name: SpacyEntityExtractor
#     dimensions: ["CARDINAL"]
#   - name: CRFEntityExtractor
#   - name: EntitySynonymMapper
#   - name: SklearnIntentClassifier

pipeline:
  - name: "components.preprocessors.ExcludePreprocessor"
  - name: SpacyNLP
    model: "en_core_web_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: SpacyTokenizer
  - name: LanguageModelFeaturizer
  - name: DIETClassifier
    constrain_similarities: True
  - name: SpacyEntityExtractor
    dimensions: ["CARDINAL"]
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 5
