language: it

pipeline:
  # - name: components.preprocessors.ExcludePreprocessor
  #   exclude: ",-."
  - name: components.preprocessors.W2NPreprocessor
  - name: WhitespaceTokenizer
  - name: LanguageModelFeaturizer
    model_name: bert
    model_weights: dbmdz/bert-base-italian-uncased
  - name: RegexFeaturizer
    case_sensitive: False
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    constrain_similarities: True
    epochs: 200
  - name: EntitySynonymMapper

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.6
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: TEDPolicy
    max_history: 5
    epochs: 5
